name: boilerplate_getx
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  build_runner: ^2.4.9
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/lottie/
